-- +migrate Up
ALTER TABLE `items`
  COMMENT '',
  MODIFY COLUMN `sUrl` varchar(200) DEFAULT NULL COMMENT 'Url of the item, as will be loaded in the iframe',
  MODIFY COLUMN `idPlatform` int(11) DEFAULT NULL COMMENT 'Platform that hosts this item',
  MODIFY COLUMN `sTextId` varchar(200) DEFAULT NULL COMMENT 'Unique string identifying the item, independently of where it is hosted',
  MODIFY COLUMN `bTitleBarVisible` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT 'Whether the title bar should be visible initially when this item is loaded',
  MODIFY COLUMN `bTransparentFolder` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Whether the breadcrumbs should hide this folder',
  MODIFY COLUMN `bDisplayDetailsInParent` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'If true, display a large icon, the subtitle, and more within the parent chapter',
  MODIFY COLUMN `bCustomChapter` tinyint(3) unsigned DEFAULT '0' COMMENT 'Whether it is a chapter where users can add their own content. Access to this chapter will not be propagated to its children',
  MODIFY COLUMN `bDisplayChildrenAsTabs` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'If true, display the children of the item (a chapter) as tabs, instead of as a list of items.',
  MODIFY COLUMN `bUsesAPI` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether the item uses the task integration API, at the minimum the load and getHeight functions.',
  MODIFY COLUMN `bReadOnly` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Prevents any modification of the scores for this item (typically, to display a contest item after the end date of the contest)',
  MODIFY COLUMN `sFullScreen` enum('forceYes','forceNo','default','') NOT NULL DEFAULT 'default' COMMENT 'Whether the item should be loaded in full screen mode (without the navigation panel and most of the top header). By default, tasks are displayed in full screen, but not chapters.',
  MODIFY COLUMN `bShowDifficulty` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Display an indication about the difficulty of each child relative to the other children',
  MODIFY COLUMN `bShowSource` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If false, we hide any information about the origin of tasks for this item and its descendants. Intended to be used during contests, so that users can''t find the solution online.',
  MODIFY COLUMN `bHintsAllowed` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether hints are allowed for tasks accessed through this chapter',
  MODIFY COLUMN `bFixedRanks` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If true, prevents users from changing the order of the children by drag&drop and auto-calculation of the iOrder of children. Allows for manual setting of the iOrder, for instance in cases where we want to have multiple items with the same iOrder (check items_items.iChildOrder).',
  MODIFY COLUMN `sValidationType` enum('None','All','AllButOne','Categories','One','Manual') NOT NULL DEFAULT 'All' COMMENT 'Criteria for this item to be considered validated, based on the status of the children. Ex: "All" means all children should be validated. Categories means items of the "Validation" category need to be validated.',
  MODIFY COLUMN `iValidationMin` int(11) DEFAULT NULL COMMENT 'Minimum score to obtain so that the item is considered as validated.',
  MODIFY COLUMN `sPreparationState` enum('NotReady','Reviewing','Ready') NOT NULL DEFAULT 'NotReady' COMMENT 'Status of preparation of this item.',
  MODIFY COLUMN `idItemUnlocked` text COMMENT 'Comma-separated list of item_ids which will be unlocked if this item is validated',
  MODIFY COLUMN `iScoreMinUnlock` int(11) NOT NULL DEFAULT '100' COMMENT 'Minimum score to obtain so that the item, indicated by "idItemUnlocked", is actually unlocked',
  MODIFY COLUMN `sSupportedLangProg` varchar(200) DEFAULT NULL COMMENT 'Comma-separated list of programming languages that this item can be solved with; not currently used.',
  MODIFY COLUMN `idDefaultLanguage` bigint(20) DEFAULT '1' COMMENT 'Default language of this task (the reference, used when comparing translations)',
  MODIFY COLUMN `sTeamMode` enum('All','Half','One','None') DEFAULT NULL COMMENT 'If idTeamInGroup is not NULL, this field specifies how many team members need to belong to that group in order for the whole team to be qualified and able to start the item.',
  MODIFY COLUMN `bTeamsEditable` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether users can create and edit their teams',
  MODIFY COLUMN `idTeamInGroup` bigint(20) DEFAULT NULL COMMENT 'group ID in which "qualified" users will belong. sTeamMode dictates how many of a team''s members must be "qualified" in order to start the item.',
  MODIFY COLUMN `iTeamMaxMembers` int(11) NOT NULL DEFAULT '0' COMMENT 'Maximum number of members of teams participating to this item',
  MODIFY COLUMN `bHasAttempts` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether team participation is mandatory. Whether users can create multiple attempts when working on this item.',
  MODIFY COLUMN `sAccessOpenDate` datetime DEFAULT NULL COMMENT 'When access to this item can be opened',
  MODIFY COLUMN `sDuration` time DEFAULT NULL COMMENT 'Not NULL if time-limited item. If so, how long users have to work on it.',
  MODIFY COLUMN `sEndContestDate` datetime DEFAULT NULL COMMENT 'Until when people can start participating to this contest',
  MODIFY COLUMN `bShowUserInfos` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Always show user infos in title bar of all descendants. Allows the teacher to see who is working on what (e.g., during an exam).',
  MODIFY COLUMN `sContestPhase` enum('Running','Analysis','Closed') NOT NULL COMMENT 'In running mode, users can only access to the tasks during their participation. In Analysis, they may look at their submissions, or try new attemps. Not sure what Closed would be.',
  MODIFY COLUMN `iLevel` int(11) DEFAULT NULL COMMENT 'On our old website, chapters were attached to a level, and we could displayed stats specific to a level.',
  MODIFY COLUMN `bNoScore` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this item should not have any score displayed / propagated to the parent.',
  MODIFY COLUMN `groupCodeEnter` tinyint(1) DEFAULT '0' COMMENT 'Whether users can enter through a group code';

-- +migrate Down
ALTER TABLE `items`
  COMMENT '',
  MODIFY COLUMN `sUrl` varchar(200) DEFAULT NULL,
  MODIFY COLUMN `idPlatform` int(11) DEFAULT NULL,
  MODIFY COLUMN `sTextId` varchar(200) DEFAULT NULL,
  MODIFY COLUMN `bTitleBarVisible` tinyint(3) unsigned NOT NULL DEFAULT '1',
  MODIFY COLUMN `bTransparentFolder` tinyint(3) unsigned NOT NULL DEFAULT '0',
  MODIFY COLUMN `bDisplayDetailsInParent` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'when true, display a large icon, the subtitle, and more within the parent chapter',
  MODIFY COLUMN `bCustomChapter` tinyint(3) unsigned DEFAULT '0' COMMENT 'true if this is a chapter where users can add their own content. access to this chapter will not be propagated to its children',
  MODIFY COLUMN `bDisplayChildrenAsTabs` tinyint(3) unsigned NOT NULL DEFAULT '0',
  MODIFY COLUMN `bUsesAPI` tinyint(1) NOT NULL DEFAULT '1',
  MODIFY COLUMN `bReadOnly` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `sFullScreen` enum('forceYes','forceNo','default','') NOT NULL DEFAULT 'default',
  MODIFY COLUMN `bShowDifficulty` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bShowSource` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bHintsAllowed` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bFixedRanks` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `sValidationType` enum('None','All','AllButOne','Categories','One','Manual') NOT NULL DEFAULT 'All',
  MODIFY COLUMN `iValidationMin` int(11) DEFAULT NULL,
  MODIFY COLUMN `sPreparationState` enum('NotReady','Reviewing','Ready') NOT NULL DEFAULT 'NotReady',
  MODIFY COLUMN `idItemUnlocked` text,
  MODIFY COLUMN `iScoreMinUnlock` int(11) NOT NULL DEFAULT '100',
  MODIFY COLUMN `sSupportedLangProg` varchar(200) DEFAULT NULL,
  MODIFY COLUMN `idDefaultLanguage` bigint(20) DEFAULT '1',
  MODIFY COLUMN `sTeamMode` enum('All','Half','One','None') DEFAULT NULL,
  MODIFY COLUMN `bTeamsEditable` tinyint(1) NOT NULL,
  MODIFY COLUMN `idTeamInGroup` bigint(20) DEFAULT NULL,
  MODIFY COLUMN `iTeamMaxMembers` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bHasAttempts` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `sAccessOpenDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sDuration` time DEFAULT NULL,
  MODIFY COLUMN `sEndContestDate` datetime DEFAULT NULL,
  MODIFY COLUMN `bShowUserInfos` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'always show user infos in title bar of all descendants',
  MODIFY COLUMN `sContestPhase` enum('Running','Analysis','Closed') NOT NULL,
  MODIFY COLUMN `iLevel` int(11) DEFAULT NULL,
  MODIFY COLUMN `bNoScore` tinyint(1) NOT NULL,
  MODIFY COLUMN `groupCodeEnter` tinyint(1) DEFAULT '0' COMMENT 'Offer users to enter through a group code';
