-- +migrate Up
ALTER TABLE `groups_attempts`
  COMMENT 'Attempts of a group (team or user) to solve a task once or several times with different parameters with the task allows it.',
  MODIFY COLUMN `iScore` float NOT NULL DEFAULT '0' COMMENT 'Current score for this attempt',
  MODIFY COLUMN `iScoreComputed` float NOT NULL DEFAULT '0' COMMENT 'Score computed for this attempt (may be manually overriden)',
  MODIFY COLUMN `iScoreReeval` float DEFAULT '0' COMMENT 'Score computed during a reevaluation. This field allows to do a reevaluation, continue it if interrupted, and then apply the reevaluated score when/if we want.',
  MODIFY COLUMN `iScoreDiffManual` float NOT NULL DEFAULT '0' COMMENT 'How much did we manually add to the computed score',
  MODIFY COLUMN `sScoreDiffComment` varchar(200) NOT NULL DEFAULT '' COMMENT 'Reason why the score was manually changed',
  MODIFY COLUMN `nbSubmissionsAttempts` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of submissions in total for this item and its children',
  MODIFY COLUMN `nbTasksTried` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of tasks which have been attempted among this item''s descendants (at least one submission), within this attempt',
  MODIFY COLUMN `nbTasksSolved` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of tasks which have been solved among this item''s descendants (at least one submission), within this attempt',
  MODIFY COLUMN `nbChildrenValidated` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of items which have been validated among this item''s direct children (solved, or read, or chapters marked as validated), within this attempt',
  MODIFY COLUMN `bValidated` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this item is validated, within this attempt (different items have different critetria for validation)',
  MODIFY COLUMN `bFinished` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this item is finished within this attempt (max score obtained for a task, every child finished for a chapter)',
  MODIFY COLUMN `bKeyObtained` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the user obtained the key on this item (changed to 1 if the user gets a score >= items.iScoreMinUnlock, will grant access to new items from items.idItemUnlocked). This information is propagated to users_items.',
  MODIFY COLUMN `nbTasksWithHelp` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of this item''s descendants tasks within this attempts for which the user asked for hints (or help on the forum - not implemented)',
  MODIFY COLUMN `sHintsRequested` mediumtext COMMENT 'JSON array of the hints that have been requested for this attempt',
  MODIFY COLUMN `nbHintsCached` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of hints which have been requested for this attempt',
  MODIFY COLUMN `nbCorrectionsRead` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of solutions that the group read among the descendants of this item, for this attempt.',
  MODIFY COLUMN `iPrecision` int(11) NOT NULL DEFAULT '0' COMMENT 'Precision (based on a formula to be defined) of the user, when working on this item and its descendants.',
  MODIFY COLUMN `iAutonomy` int(11) NOT NULL DEFAULT '0' COMMENT 'Autonomy (based on a formula to be defined) of the user, when working on this item and its descendants (how much help / hints he used)',
  MODIFY COLUMN `sStartDate` datetime DEFAULT NULL COMMENT 'When the item was started for this attempt. Can be different from when the attempt was created.',
  MODIFY COLUMN `sValidationDate` datetime DEFAULT NULL COMMENT 'When the item was validated, within this attempt.',
  MODIFY COLUMN `sFinishDate` datetime DEFAULT NULL COMMENT 'When the item was finished, within this attempt.',
  MODIFY COLUMN `sLastActivityDate` datetime DEFAULT NULL COMMENT 'When the last activity within this task.',
  MODIFY COLUMN `sThreadStartDate` datetime DEFAULT NULL COMMENT 'When the discussion thread was started by this group on the forum',
  MODIFY COLUMN `sBestAnswerDate` datetime DEFAULT NULL COMMENT 'When this group obtained its best score so far on this attempt.',
  MODIFY COLUMN `sLastAnswerDate` datetime DEFAULT NULL COMMENT 'When the last answer was provided by this group on this attempt',
  MODIFY COLUMN `sLastHintDate` datetime DEFAULT NULL COMMENT 'When the last hint has been obtained for this attempt',
  MODIFY COLUMN `sContestStartDate` datetime DEFAULT NULL COMMENT 'When the user started the timer (if this item is time-limited)',
  MODIFY COLUMN `bRanked` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this attempt is official for this item (as opposed to an extra attempt after an exam has ended, for example)',
  MODIFY COLUMN `sAllLangProg` varchar(200) DEFAULT NULL COMMENT 'List of programming languages used',
  MODIFY COLUMN `sAncestorsComputationState` enum('done','processing','todo','temp') NOT NULL DEFAULT 'done'  COMMENT 'Whether the data was propagated to the users'' individual users_items.'
  ;

-- +migrate Down
ALTER TABLE `groups_attempts`
  COMMENT '',
  MODIFY COLUMN `idGroup` bigint(20) NOT NULL,
  MODIFY COLUMN `idItem` bigint(20) NOT NULL,
  MODIFY COLUMN `idUserCreator` bigint(20) DEFAULT NULL,
  MODIFY COLUMN `iOrder` int(11) NOT NULL,
  MODIFY COLUMN `iScore` float NOT NULL DEFAULT '0',
  MODIFY COLUMN `iScoreComputed` float NOT NULL DEFAULT '0',
  MODIFY COLUMN `iScoreReeval` float DEFAULT '0',
  MODIFY COLUMN `iScoreDiffManual` float NOT NULL DEFAULT '0',
  MODIFY COLUMN `sScoreDiffComment` varchar(200) NOT NULL DEFAULT '',
  MODIFY COLUMN `nbSubmissionsAttempts` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `nbTasksTried` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `nbTasksSolved` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `nbChildrenValidated` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bValidated` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bFinished` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bKeyObtained` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `nbTasksWithHelp` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `sHintsRequested` mediumtext,
  MODIFY COLUMN `nbHintsCached` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `nbCorrectionsRead` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `iPrecision` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `iAutonomy` int(11) NOT NULL DEFAULT '0',
  MODIFY COLUMN `sStartDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sValidationDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sFinishDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sLastActivityDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sThreadStartDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sBestAnswerDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sLastAnswerDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sLastHintDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sContestStartDate` datetime DEFAULT NULL,
  MODIFY COLUMN `bRanked` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `sAllLangProg` varchar(200) DEFAULT NULL,
  MODIFY COLUMN `sAncestorsComputationState` enum('done','processing','todo','temp') NOT NULL DEFAULT 'done'
  ;
