-- +migrate Up
ALTER TABLE `groups_items`
  COMMENT 'Access given to a group on a specific item, both directly and inherited from ancestor items.',
  MODIFY COLUMN `idUserCreated` bigint(20) NOT NULL COMMENT 'User who created the entry',
  MODIFY COLUMN `sPartialAccessDate` datetime DEFAULT NULL COMMENT 'At what date the group obtains partial access to the item',
  MODIFY COLUMN `sAccessReason` varchar(200) DEFAULT NULL COMMENT 'Manual comment about why the current access was given',
  MODIFY COLUMN `sFullAccessDate` datetime DEFAULT NULL COMMENT 'At what date the group obtains full access to the item',
  MODIFY COLUMN `sAccessSolutionsDate` datetime DEFAULT NULL COMMENT 'At what date the group obtains solution access to the item',
  MODIFY COLUMN `bOwnerAccess` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the group has owner access to this item',
  MODIFY COLUMN `bManagerAccess` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the group has manager access to this item (not inherited)',
  MODIFY COLUMN `sCachedFullAccessDate` datetime DEFAULT NULL COMMENT 'At what date the user obtains full access, taking into account access inherited from the ancestors',
  MODIFY COLUMN `sCachedPartialAccessDate` datetime DEFAULT NULL COMMENT 'At what date the user obtains partial access, taking into account access inherited from the ancestors',
  MODIFY COLUMN `sCachedAccessSolutionsDate` datetime DEFAULT NULL COMMENT 'At what date the user obtains solution access, taking into account access inherited from the ancestors',
  MODIFY COLUMN `sCachedGrayedAccessDate` datetime DEFAULT NULL COMMENT 'At what date the user obtains grayed access (can see the title but not the content), taking into account access inherited from the ancestors',
  MODIFY COLUMN `sCachedAccessReason` varchar(200) DEFAULT NULL COMMENT 'How was the current access obtained (generated from reasons given manually to ancestor items)',
  MODIFY COLUMN `bCachedFullAccess` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the group currently has full access to this item',
  MODIFY COLUMN `bCachedPartialAccess` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the group currently has partial access to this item',
  MODIFY COLUMN `bCachedAccessSolutions` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the group currently has solution access to this item',
  MODIFY COLUMN `bCachedGrayedAccess` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the group currently has grayed access to this item',
  MODIFY COLUMN `bCachedManagerAccess` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the group currently has manager access to this item',
  MODIFY COLUMN `sPropagateAccess` enum('self','children','done') NOT NULL DEFAULT 'self' COMMENT 'Internal state used for access propagation',
  MODIFY COLUMN `sAdditionalTime` time DEFAULT NULL COMMENT 'Time that was attributed (can be negative) to this group for this item (typically, for  time-limited items)';

-- +migrate Down
ALTER TABLE `groups_items`
  COMMENT '',
  MODIFY COLUMN `idUserCreated` bigint(20) NOT NULL,
  MODIFY COLUMN `sPartialAccessDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sAccessReason` varchar(200) DEFAULT NULL,
  MODIFY COLUMN `sFullAccessDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sAccessSolutionsDate` datetime DEFAULT NULL,
  MODIFY COLUMN `bOwnerAccess` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bManagerAccess` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'not for inherited access',
  MODIFY COLUMN `sCachedFullAccessDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sCachedPartialAccessDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sCachedAccessSolutionsDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sCachedGrayedAccessDate` datetime DEFAULT NULL,
  MODIFY COLUMN `sCachedAccessReason` varchar(200) DEFAULT NULL,
  MODIFY COLUMN `bCachedFullAccess` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bCachedPartialAccess` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bCachedAccessSolutions` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bCachedGrayedAccess` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `bCachedManagerAccess` tinyint(1) NOT NULL DEFAULT '0',
  MODIFY COLUMN `sPropagateAccess` enum('self','children','done') NOT NULL DEFAULT 'self',
  MODIFY COLUMN `sAdditionalTime` time DEFAULT NULL;
