basePath: '{{.BasePath}}'
definitions:
  items.LocalizedTitle:
    properties:
      language_id:
        $ref: '#/definitions/types.RequiredInt64'
        type: object
      title:
        $ref: '#/definitions/types.RequiredString'
        type: object
    type: object
  items.NewItemRequest:
    properties:
      id:
        $ref: '#/definitions/types.OptionalInt64'
        type: object
      parents:
        items:
          $ref: '#/definitions/items.ParentRef'
        type: array
      strings:
        items:
          $ref: '#/definitions/items.LocalizedTitle'
        type: array
      type:
        $ref: '#/definitions/types.RequiredString'
        type: object
    type: object
  items.NewItemResponse:
    properties:
      ID:
        type: integer
    type: object
  items.ParentRef:
    properties:
      id:
        $ref: '#/definitions/types.RequiredInt64'
        type: object
      order:
        $ref: '#/definitions/types.RequiredInt64'
        type: object
    type: object
  types.OptionalInt64:
    properties:
      "null":
        type: boolean
      set:
        type: boolean
      value:
        type: integer
    type: object
  types.RequiredInt64:
    properties:
      "null":
        type: boolean
      set:
        type: boolean
      value:
        type: integer
    type: object
  types.RequiredString:
    properties:
      "null":
        type: boolean
      set:
        type: boolean
      value:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: Algorea Backend API
  version: '{{.Version}}'
paths:
  /items/:
    post:
      consumes:
      - application/json
      description: Add an item within a hierarchy.
      operationId: add-item
      parameters:
      - description: '{}'
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/items.NewItemRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/items.NewItemResponse'
            type: object
      security:
      - cookieAuth: []
      summary: Add an item
securityDefinitions:
  cookieAuth:
    in: Cookie
    name: PHPSESSID
    type: apiKey
swagger: "2.0"
