linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/France-ioi/AlgoreaBackend/v2/app/logging.SharedLogger).Debugf
          - (github.com/France-ioi/AlgoreaBackend/v2/app/logging.SharedLogger).Infof
          - (github.com/France-ioi/AlgoreaBackend/v2/app/logging.SharedLogger).Warnf
          - (github.com/France-ioi/AlgoreaBackend/v2/app/logging.SharedLogger).Errorf
          - (github.com/France-ioi/AlgoreaBackend/v2/app/logging.SharedLogger).Panicf
          - (github.com/France-ioi/AlgoreaBackend/v2/app/logging.SharedLogger).Fatalf
          - github.com/France-ioi/AlgoreaBackend/v2/app/logging.Debugf
          - github.com/France-ioi/AlgoreaBackend/v2/app/logging.Infof
          - github.com/France-ioi/AlgoreaBackend/v2/app/logging.Warnf
          - github.com/France-ioi/AlgoreaBackend/v2/app/logging.Errorf
          - github.com/France-ioi/AlgoreaBackend/v2/app/logging.Panicf
          - github.com/France-ioi/AlgoreaBackend/v2/app/logging.Fatalf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to be used only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/France-ioi/AlgoreaBackend/v2
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - whyNoLint # Requires an explanation for each nolint. requires many changes

linters:
  enable-all: true
  disable:
    - deadcode         # Deprecated.
    - exhaustivestruct # Deprecated.
    - golint           # Deprecated.
    - ifshort          # Deprecated.
    - interfacer       # Deprecated.
    - maligned         # Deprecated.
    - nosnakecase      # Deprecated.
    - scopelint        # Deprecated.
    - structcheck      # Deprecated.
    - varcheck         # Deprecated.
    - prealloc         # Note from authors: For most programs usage of prealloc will be a premature optimization.
    - gochecknoglobals
    - testpackage      # Requires that go tests files are in a different package, but current tests are on private functions
    - wsl              # Requires whitelines between blocks. requires many changes, enable it later
    - gomnd            # Flags all "magic numbers" in the code. requires many changes
    - goerr113         # Don't allow dynamic errors, requires wrapped static errors. requires many changes
    - nestif           # Doesn't allow too long nested if. requires complex changes
    - forbidigo        # For update to go1.20
    - gci              # For update to go1.20
    - gochecknoinits   # For update to go1.20
    - asasalint        # For update to go1.20
    - containedctx     # For update to go1.20
    - contextcheck     # For update to go1.20
    - cyclop           # For update to go1.20
    - dupword          # For update to go1.20
    - errchkjson       # For update to go1.20
    - errorlint        # For update to go1.20
    - errname          # For update to go1.20
    - execinquery      # For update to go1.20
    - exhaustive       # For update to go1.20
    - forcetypeassert  # For update to go1.20
    - ireturn          # For update to go1.20
    - maintidx         # For update to go1.20
    - musttag          # For update to go1.20
    - nilnil           # For update to go1.20
    - nlreturn         # For update to go1.20
    - noctx            # For update to go1.20
    - nonamedreturns   # For update to go1.20
    - paralleltest     # For update to go1.20
    - sqlclosecheck    # For update to go1.20
    - tagliatelle      # For update to go1.20
    - tenv             # For update to go1.20
    - thelper          # For update to go1.20
    - usestdlibvars    # For update to go1.20
    - varnamelen       # For update to go1.20
    - wrapcheck        # For update to go1.20
    - exhaustruct      # For update to go1.20
    - gomoddirectives  # For update to go1.20
    - dupl             # For update to go1.20

run:
  skip-dirs:
    - db
    - app/database/testdata
    - test-results
    - pkg/golinters/goanalysis/(checker|passes)
    - app/doc

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
        - gocognit
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - text: "is too long"
      linters:
        - funlen
    - text: "has too many statements"
      linters:
        - funlen
    - text: unknown JSON option "squash" # an option provided by the mapstructure library and the formdata package
      linters:
        - staticcheck
    - text: "function has more than 5 results, consider to simplify the function"
      linters:
        - gocritic
    - text: "to be of non-pointer type"
      linters:
        - gocritic
    - text: "SA1019:" # io/util has been deprecated since Go 1.19
      linters:
        - staticcheck
    - text: "ptrToRefParam:"
      linters:
        - gocritic
    - text: "G404:" # Use of weak random number generator (math/rang instead of crypto/rand)
      linters:
        - gosec
    - text: "deferInLoop:" # Possible resource leak, 'defer' is called in the 'for' loop.
      linters:
        - gocritic
    - text: "type .answerSubmitResponse. is unused"
      linters:
        - unused
    - text: "uncheckedInlineErr: err error is unchecked, maybe intended to check it instead of conn.db.AddError.err."
      linters:
        - gocritic
    - text: "timeCmpSimplify:"
      linters:
        - gocritic

  exclude:
    - "not declared by package utf8"
    - "unicode/utf8/utf8.go"
  max-issues-per-linter: 0
  max-same-issues: 0
  #fix: true # Enable to try auto fix.

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.52.2 # use the fixed version to not introduce new linters unexpectedly
