linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/github.com/sirupsen/logrus.Entry).Debugf
          - (github.com/github.com/sirupsen/logrus.Entry).Infof
          - (github.com/github.com/sirupsen/logrus.Entry).Warnf
          - (github.com/github.com/sirupsen/logrus.Entry).Errorf
          - (github.com/github.com/sirupsen/logrus.Entry).Panicf
          - (github.com/github.com/sirupsen/logrus.Entry).Fatalf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to be used only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/France-ioi/AlgoreaBackend/v2
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - whyNoLint # Requires an explanation for each nolint. requires many changes
  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`.
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      #- blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - default # Default section: contains all imports that could not be matched to another section type.
      #- prefix(github.com/org/project) # Custom section: groups all imports with the specified Prefix.
      #- dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      #- alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
      #- localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
      - prefix(github.com/France-ioi/AlgoreaBackend/v2/) # Custom section: groups all imports with the specified Prefix.
    # Checks that no inline comments are present.
    # Default: false
    no-inline-comments: false
    # Checks that no prefix comments (comment lines above an import) are present.
    # Default: false
    no-prefix-comments: false
    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    # Default: false
    custom-order: true
    # Drops lexical ordering for custom sections.
    # Default: false
    no-lex-order: false

linters:
  enable-all: true
  disable:
    - deadcode         # Deprecated.
    - exhaustivestruct # Deprecated.
    - golint           # Deprecated.
    - ifshort          # Deprecated.
    - interfacer       # Deprecated.
    - maligned         # Deprecated.
    - nosnakecase      # Deprecated.
    - scopelint        # Deprecated.
    - structcheck      # Deprecated.
    - varcheck         # Deprecated.
    - gochecknoglobals
    - testpackage      # Requires that go tests files are in a different package, but current tests are on private functions
    - wsl              # Requires whitelines between blocks. requires many changes, enable it later
    - goerr113         # Don't allow dynamic errors, requires wrapped static errors. requires many changes
    - contextcheck     # For update to go1.20
    - cyclop           # For update to go1.20
    - dupword          # For update to go1.20
    - errchkjson       # For update to go1.20
    - errorlint        # For update to go1.20
    - errname          # For update to go1.20
    - execinquery      # For update to go1.20
    - exhaustive       # For update to go1.20
    - forcetypeassert  # For update to go1.20
    - ireturn          # For update to go1.20
    - maintidx         # For update to go1.20
    - musttag          # For update to go1.20
    - nilnil           # For update to go1.20
    - nlreturn         # For update to go1.20
    - noctx            # For update to go1.20
    - nonamedreturns   # For update to go1.20
    - paralleltest     # For update to go1.20
    - sqlclosecheck    # For update to go1.20
    - tagliatelle      # For update to go1.20
    - tenv             # For update to go1.20
    - thelper          # For update to go1.20
    - usestdlibvars    # For update to go1.20
    - varnamelen       # For update to go1.20
    - wrapcheck        # For update to go1.20
    - exhaustruct      # For update to go1.20
    - gomoddirectives  # For update to go1.20
    - dupl             # For update to go1.20

run:
  skip-dirs:
    - db
    - app/database/testdata
    - test-results
    - pkg/golinters/goanalysis/(checker|passes)
    - app/doc

issues:
  exclude-use-default: false
  exclude-rules:
    - text: "is too long"
      linters:
        - funlen
    - text: "has too many statements"
      linters:
        - funlen
    - text: unknown JSON option "squash" # an option provided by the mapstructure library and the formdata package
      linters:
        - staticcheck
    - text: "timeCmpSimplify:" # this one suggests replacing !After() with Before() which is not correct
      linters:
        - gocritic

  exclude:
    - "not declared by package utf8"
    - "unicode/utf8/utf8.go"
  max-issues-per-linter: 0
  max-same-issues: 0
  #fix: true # Enable to try auto fix.

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.52.2 # use the fixed version to not introduce new linters unexpectedly
