version: '3'
services:
  # connect from host using: "mysql -hlocalhost -Dalgorea_db -ualgorea -pa_db_password --protocol=TCP"
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=10485760
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: a_root_db_password
      MYSQL_USER: algorea
      MYSQL_PASSWORD: a_db_password
      MYSQL_DATABASE: algorea_db
      MYSQL_ROOT_HOST: "%"
    security_opt:
      - seccomp:unconfined
  backend:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      ALGOREA_ENV: dev
      ALGOREA_DATABASE__ADDR: db
      ALGOREA_DATABASE__USER: algorea
      ALGOREA_DATABASE__PASSWD: a_db_password
      ALGOREA_DATABASE__DBNAME: algorea_db
      ALGOREA_LOGGING__FORMAT: text
      ALGOREA_LOGGING__OUTPUT: stdout
      ALGOREA_LOGGING__LOGSQLQUERIES: 0
      ALGOREA_LOGGING__LEVEL: debug
    command: >
      /bin/sh -c "
        echo \"Wait 1sec for MySQL to be ready...\";
        sleep 2;
        AlgoreaBackend serve;
      "
