version: '3'
services:
  # connect from host using: "mysql -hlocalhost -Dalgorea_db -ualgorea -pa_db_password --protocol=TCP"
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=10485760
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a_root_db_password
      MYSQL_USER: algorea
      MYSQL_PASSWORD: a_db_password
      MYSQL_DATABASE: algorea_db
  # former_platform:
  #   image: franceioi/algoreaplatform:latest
  #   ports:
  #   - "8080:80"
  #   links:
  #   - db
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_NAME: algorea_db
  #     DATABASE_USER: algorea
  #     DATABASE_PASSWORD: a_db_password
