version: '3'
services:
  # connect from host using: "mysql -hlocalhost -Dalgorea_db -ualgorea -pa_db_password --protocol=TCP"
  db:
    image: mysql:8.0.34
    command: --default-authentication-plugin=caching_sha2_password --max-allowed-packet=10485760 --innodb_lock_wait_timeout=5 --innodb_ft_min_token_size=1 --skip-log-bin
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: a_root_db_password
      MYSQL_USER: algorea
      MYSQL_PASSWORD: a_db_password
      MYSQL_DATABASE: algorea_db
      MYSQL_ROOT_HOST: "%"
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  db_test:
    image: mysql:8.0.34
    command: --default-authentication-plugin=caching_sha2_password --innodb_lock_wait_timeout=5 --innodb_ft_min_token_size=1 --skip-log-bin
    restart: always
    ports:
      - "3307:3306"
      - "33070:33060"
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
        tmpfs:
          size: 314572800 # Size in bytes, 300MB
    environment:
      MYSQL_ROOT_PASSWORD: a_root_db_password
      MYSQL_USER: algorea
      MYSQL_PASSWORD: a_db_password
      MYSQL_DATABASE: algorea_db
      MYSQL_ROOT_HOST: "%"
    security_opt:
      - seccomp:unconfined
  backend:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      ALGOREA_ENV: dev
      ALGOREA_DATABASE__ADDR: db
      ALGOREA_DATABASE__USER: algorea
      ALGOREA_DATABASE__PASSWD: a_db_password
      ALGOREA_DATABASE__DBNAME: algorea_db
      ALGOREA_LOGGING__FORMAT: text
      ALGOREA_LOGGING__OUTPUT: stdout
      ALGOREA_LOGGING__LOGSQLQUERIES: 0
      ALGOREA_LOGGING__LEVEL: debug
    volumes:
      - ./db/migrations/:/go/src/AlgoreaBackend/db/migrations/:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      /bin/sh -c "
        echo \"Wait 1sec for MySQL to be ready...\";
        sleep 2;
        AlgoreaBackend serve;
      "
volumes:
  mysql-volume:
