#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=AM  -- '*.feature')

if [ -n "$files" ]; then
    if grep -H "^[ \t]*@" $files; then
        echo "Blocking commit as a @tag was found."
        exit 1
    fi
fi
