#!/bin/sh

featureFiles=$(git diff --cached --name-only --diff-filter=AM  -- '*.feature')
if [ -n "$featureFiles" ]; then
    if grep -H "^[ \t]*@" $featureFiles; then
        echo "Blocking commit as a @tag was found."
        exit 1
    fi
fi

git diff --cached --name-only | if grep --quiet ".circleci/config.yml"
then
    echo "Checking circleci config... To install circleci cli, check https://circleci.com/docs/local-cli/"
    circleci config validate
fi
