version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /home/circleci/France-ioi/AlgoreaBackend
    environment:
    steps:
      - checkout
      - run:
          name: Compile project
          command: make build
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  unit-tests:
    docker:
      - image: circleci/golang:1.11
    working_directory: /home/circleci/France-ioi/AlgoreaBackend
    environment:
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run unit tests
          command: make test-unit-report
      - store_test_results: &TESTPATH
          path: test-results
      - store_artifacts: *TESTPATH
      - run:
          name: Upload test coverage results to Codecov
          command: bash <(curl -s https://codecov.io/bash)
  bdd-tests:
    docker:
      - image: circleci/golang:1.11
      - image: circleci/mysql:5.6
        environment:
          MYSQL_USER: alg_ci_user
          MYSQL_PASSWORD: dummy_password
          MYSQL_DATABASE: ci_db
    working_directory: /home/circleci/France-ioi/AlgoreaBackend
    environment:
      ALGOREA_DATABASE.CONNECTION.ADDR: 127.0.0.1
      ALGOREA_DATABASE.CONNECTION.USER: alg_ci_user
      ALGOREA_DATABASE.CONNECTION.PASSWD: dummy_password
      ALGOREA_DATABASE.CONNECTION.DBNAME: ci_db
    steps:
      - attach_workspace:
          at: ./
      - run: sudo apt-get install mysql-client # required for db-restore
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 30s
      - run:
          name: Recreate database
          command: |
            go run main.go db-restore
            go run main.go db-migrate
      - run:
          name: Run BDD Tests
          command: make test-bdd-report
      - run:
          when: on_fail
          name: Run BDD Tests (detailed)
          command: /tmp/go/bin/godog --format=pretty
      - store_test_results: *TESTPATH
      - store_artifacts: *TESTPATH
  lint:
    docker:
      - image: circleci/golang:1.11
    working_directory: /home/circleci/France-ioi/AlgoreaBackend
    environment:
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run metalinter
          command: GOMODULE111=off make lint # gometalinter doesn't support Go modules yet
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - unit-tests:
          requires:
          - build
      - bdd-tests:
          requires:
          - build
      - lint:
          requires:
          - build
