server:
  port: 8080
  rootPath: "/" # the path at which the router is mounted
  compress: false # whether compression is enabled by default
  # domainOverride: dev.algorea.org # use this domain name for cookies and per-domain configuration choosing
  propagation_endpoint: "" # Endpoint to schedule the propagation asynchronously. If empty, propagation is synchronous.
  disable_results_propagation: false # Disable the propagation of results.
auth:
  loginModuleURL: "http://127.0.0.1:8000"
  clientID: "1"
  clientSecret: "tzxsLyFtJiGnmD6sjZMqSEidVpVsL3hEoSxIXCpI"
token:
  platformName: algrorea_backend
  publicKeyFile: public_key.pem # one of (publicKeyFile, publicKey) is required
  #publicKey: |
  #  -----BEGIN PUBLIC KEY-----
  #  MIIBIjAN...
  #  -----END PUBLIC KEY-----
  privateKeyFile: private_key.pem # one of (privateKeyFile, privateKey) is required
database:
  user: algorea
  passwd: a_db_password
  addr: localhost:3307 # TEST CONFIG WARNING: Running the tests erases the database, DO NOT USE A LIVE DATABASE
  net: tcp
  #dbname: algorea_db
  allownativepasswords: true
logging:
  format: console # text, json, console (colorized multiline text, suitable for development)
  output: stdout # stdout, stderr, file
  level: debug # debug, info, warning, error, fatal, panic
  logSQLQueries: true
  logRawSQLQueries: false
  analyzeSQLQueries: false # run EXPLAIN ANALYZE on all SQL queries (works only if logSQLQueries is true)
domains:
  -
    domains: [default] # of a list of domains
    allUsersGroup: 3
    tempUsersGroup: 2
