server:
  port: 8080
  rootpath: "/" # the path at which the router is mounted
database:
  connection:
    user: algorea
    passwd: a_db_password
    addr: localhost
    dbname: algorea_db
    allownativepasswords: true
    parseTime: true # required for the migration system
logging:
  format: json # text, json
  output: file # stdout, stderr, file
  level: debug # debug, info, warning, error, fatal, panic
  logSQLQueries: true
# reverseProxy: # server to which requests which do not match any route will be sent
#   server: "http://localhost:3000"
