server:
  port: 8080
  rootpath: "/" # the path at which the router is mounted
database:
  user: algorea
  passwd: a_db_password
  addr: localhost
  dbname: algorea_db
  allownativepasswords: true
  parseTime: true # required for the migration system
logging:
  textlogging: true
  loglevel: warning # debug, info, warning, error, fatal, panic

# reverseProxy: # server to which requests which do not match any route will be sent
#   server: "http://localhost:3000"
